== About

=== What is the {project-name} project?

The {project-name} project is a collaborative software development effort aimed at creating a robust, commercial-grade, featureful, and freely-available implementation of Documentation and Mocking REST API framework. The project is jointly managed by a group of volunteers located around the world, using the Internet and the Web to communicate, plan, and develop the framework and its related documentation. This project is part of the http://uniknow.bitbucket.org/[UniKnow community]. In addition, hundreds of users have contributed ideas, code, and documentation to the project. This file is intended to briefly describe the history of the {project-name} project and recognize the many contributors.

=== Getting involved.

If you just want to send in an occasional suggestion/fix you can use the {issue-management}[issue tracking system]. There's a lot of information about the development process to be found at *TODO: Contributors/Developers guideline*.

=== Development

There is a core group of contributors, formed initially of the project founders, and augmented from time to time by other outstanding contributors. There are 'committers', who are granted access to the source code control repositories to help maintain the project or docs, and the core group now managing the project, which is called the Project Management Committee (PMC, for short).

The project is a meritocracy -- the more work you have done, the more you will be allowed to do. The group founders set the original rules, but they can be changed by vote of the active PMC members. There is a group of people who have logins on our server and access to the source code repositories. Everyone has read-only access to the repositories.

Our primary method of communication is our {issue-management}[Issue Management] system. We discuss new features to add, bug fixes, user problems, developments, release dates, etc. The actual code development takes place on the developers' local machines, with proposed changes communicated using a pull request, and then applied to the source code control repositories by one of the committers. Anyone on the mailing list can vote on a particular issue, but only those made by active members or people who are known to be experts are counted towards the requirements for committing. Vetoes must be accompanied by a convincing technical justification.

New members of the Apache HTTP Project Management Committee are added when a frequent contributor is nominated by one member and unanimously approved by the voting members. In most cases, this "new" member has been actively contributing to the group's work for over six months, so it's usually an easy decision.

The project guidelines continuously evolve under the oversight of the PMC, as the membership of the group changes and our development/coordination tools improve.

=== Why {project-name} is free

Uniknow exists to provide robust and commercial-grade reference implementations of many types of software. It must remain a platform upon which individuals and institutions can build reliable systems, both for experimental purposes and for mission-critical purposes. We believe that the tools should be in the hands of everyone, and that software companies should make their money by providing value-added services such as specialized modules and support, amongst other things. We realize that it is often seen as an economic advantage for one company to "own" a market - in the software industry, that means to control tightly a particular conduit such that all others must pay for its use. This is typically done by "owning" the tools. As long as the tools remain "unowned" by a single company, the market will remain a level playing field for companies large and small. Thus, "ownership" of the tools must be prevented.

Furthermore, the UniKnow community is an organic entity; those who benefit from this software by using it, often contribute back to it by providing feature enhancements, bug fixes, and support for others in public lists and newsgroups. The effort expended by any particular individual is usually fairly light, but the resulting product is made very strong. These kinds of communities can only happen with freely available software -- when someone has paid for software, they usually aren't willing to fix its bugs for free. One can argue, then, that UniKnow's strength comes from the fact that it's free, and if it were made "not free" it would suffer tremendously, even if that money were spent on a real development team.

We want to see UniKnow Software used very widely -- by large companies, small companies, research institutions, schools, individuals, in the intranet environment, everywhere -- even though this may mean that companies who could afford commercial software, and would pay for it without blinking, might get a "free ride" by using UninKnow provided tools. We are even happy when some commercial software companies completely drop their own development plans and use our tools as a base, with the proper attributions as described in the LICENSE. That is to say, the UniKnow tools only comes from the UniKnow community, but many vendors ship their own product "based on the UniKnow tools".


